version: "3.0"
services:

  # All Database setup 
  # PostgreSQL 
  sql_db:
    container_name: sql_db
    image: postgres:alpine
    restart: always
    networks:
      - main-network
    environment:
      POSTGRES_PASSWORD : $SQL_PASS
      POSTGRES_USER : $SQL_USER
      POSTGRES_DB : $SQL_DB
    volumes:
      - ./Database/pg:/var/lib/postgresql/data

  # Mongo Setup 
  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    networks:
      - main-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    volumes:
      - ./Database/mongodb:/data/db

  # Setup Redis For Caching 
  redis_db:
    container_name: redis_db
    image: redis:alpine
    restart: always
    networks:
      - main-network
    volumes:
      - ./Database/redis:/usr/local/etc/redis

  # Setup Elastic Search 
  elastic_db:
    container_name: elastic_db
    image: blacktop/elasticsearch:latest
    restart: always
    networks:
      - main-network
    volumes:
      - ./Database/elasticsearch:/usr/share/elasticsearch/data


# Setup all network requirement 
networks:
  main-network:
    driver: bridge